[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.9.0"
  PNPM_VERSION = "10.2.0"
  COREPACK_ENABLE = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
