sonar.projectKey=JoaccoG_portfolio
sonar.organization=joaccog

sonar.projectName=Portfolio

sonar.sourceEncoding=UTF-8

sonar.sources=./src

sonar.exclusions=src/**/*.d.ts, src/components/icons/**/*.ts, src/components/icons/**/*.tsx, src/main.tsx

sonar.test.inclusions=src/**/*.test.ts, src/**/*.test.tsx
sonar.coverage.exclusions=src/**/*.d.ts, src/**/*.test.ts, src/**/*.test.tsx, src/test/helpers/**/*.ts, src/test/helpers/**/*.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
