sonar.projectKey=JoaccoG_portfolio
sonar.organization=joaccog

sonar.projectName=Portfolio

sonar.sourceEncoding=UTF-8

sonar.sources=./src

sonar.exclusions=src/**/*.d.ts, src/components/icons/**/*.{ts,tsx}, src/main.tsx

sonar.test.inclusions=src/**/*.test.{ts,tsx}
sonar.coverage.exclusions=src/**/*.test.{ts,tsx}, src/test/helpers/**/*.{ts,tsx}

sonar.javascript.lcov.reportPaths=coverage/lcov.info
