name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: (>) Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: (>) Check "GitHub Secrets" exists
        run: |
          if [[ -z "${{ secrets.SONAR_TOKEN }}" ]]; then
            echo "Error: SONAR_TOKEN is not set."
            exit 1
          fi

      - name: (>) Cache "pnpm"
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: (>) Install pnpm
        run: npm install -g pnpm

      - name: (>) Install dependencies
        run: pnpm install

      - name: (>) Generate unit tests coverage
        run: pnpm vitest --coverage

      - name: (>) Save coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: (>) SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov.info
